[package]
name = "firmware-esp32"
version = "0.0.1"
edition = "2024"
rust-version = "1.88"

[[bin]]
name = "esp32"
path = "src/bin/main.rs"

[dependencies]
esp-hal                 = { version = "~1.2.1", features = ["defmt", "esp32"] }
esp-bootloader-esp-idf  = { version = "0.5.0", features = ["defmt", "esp32"] }
esp-println             = { version = "0.18.0", features = ["defmt-espflash", "esp32"] }
defmt                   = "1.0.1"
critical-section        = "1.2.0"
logger                  = { path = "../../crates/logger", default-features = false, features = ["embedded"] }

[workspace]

[profile.release]
codegen-units = 1
debug = 2
lto = "fat"
opt-level = "s"
