[package]
edition      = "2024"
name         = "firmware-esp32c3"
rust-version = "1.88"
version      = "0.0.1"

[[bin]]
name = "esp32c3"
path = "./src/bin/main.rs"

[dependencies]
esp-hal                 = { version = "~1.2.1", features = ["defmt", "esp32c3"] }
esp-bootloader-esp-idf  = { version = "0.5.0", features = ["defmt", "esp32c3"] }
esp-println             = { version = "0.18.0", features = ["defmt-espflash", "esp32c3"] }
logger                  = { path = "../../crates/logger", default-features = false, features = ["embedded"] }
defmt                   = "1.0.1"
critical-section        = "1.2.0"

[workspace]

[profile.release]
codegen-units = 1
debug = 2
lto = "fat"
opt-level = "s"
