[package]
edition      = "2024"
name         = "firmware-esp32c3"
rust-version = "1.88"
version      = "0.0.1"

[[bin]]
name = "esp32c3"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.1.0", features = ["defmt", "esp32c3"] }


defmt                  = "1.0.1"
esp-bootloader-esp-idf = { version = "0.5.0", features = ["defmt", "esp32c3"] }

critical-section = "1.2.0"
esp-println      = { version = "0.17.0", features = ["defmt-espflash", "esp32c3"] }

